apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  selector: { matchLabels: { app: cloudflared } }
  template:
    metadata: { labels: { app: cloudflared } }
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest # {"$imagepolicy": "flux-system:cloudflared"}
        args: ["tunnel","--no-autoupdate","--metrics","0.0.0.0:2000","run"]
        env:
        - name: TUNNEL_TOKEN
          valueFrom: { secretKeyRef: { name: tunnel-token, key: token } }
        livenessProbe:
          httpGet: { path: /ready, port: 2000 }
