apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  namespace: ingress
data:
  Caddyfile: |
    :8080 {
      handle_host photos.example.com {
        reverse_proxy http://immich.dmz.svc.cluster.local:8080
      }
      handle_host nas.example.com {
        reverse_proxy http://192.168.1.50:5000
      }
      handle_host ups.example.com {
        reverse_proxy http://192.168.1.60:80
      }
    }
