apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - cilium
  - nfs-csi
  - local-path
  - policies
  - ingress
  - tailscale-apiserver
  - cnpg
  - image-automation
  - kube-vip
  # - longhorn    # Optional: enable if you adopt Longhorn later
