apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infra/namespaces/dmz-ns.yaml
  - pvc.yaml
  - secret.db-url.yaml
  - deploy.yaml
  - svc.yaml
  - np-egress.yaml
  - np-ingress-from-caddy.yaml
