apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imagerepository-immich.yaml
  - imagepolicy-immich.yaml
  - imagerepository-cloudflared.yaml
  - imagepolicy-cloudflared.yaml
  - imagerepository-minio.yaml
  - imagepolicy-minio.yaml
  - imagerepository-postgresql.yaml
  - imagepolicy-postgresql.yaml
  - imageupdateautomation.yaml
