apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-pg
  namespace: work
  labels: { app: app-pg }
spec:
  instances: 1
  storage:
    size: 100Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: app-pg-credentials
