apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infra/namespaces/work-ns.yaml
  - ../../infra/cnpg/repo.yaml
  - ../../infra/cnpg/release.yaml
  - ../../infra/local-path/release.yaml
  - secret.credentials.yaml
  - cluster.yaml
  - pgdump-pvc.yaml
  - pgdump-cron.yaml
  - np-allow-from-dmz.yaml
