apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-dumps
  namespace: work
spec:
  accessModes: [ ReadWriteMany ]
  storageClassName: synology-nfs
  resources: { requests: { storage: 200Gi } }
