apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.50          # EDIT ME
  share: /volume1/k8s-nfs       # EDIT ME
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
